### ISSUE TITLE
Bad Certificate

### ISSUE THREAD

**Issue by raghavmishra** [jconwell/secret_handshake#2]
Hi,
I am getting this error now,
`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:997)`
Can you please check that?

**Comment by jconwell** [comment]
That's interesting. Could you give me the full call stack?

**Comment by raghavmishra** [comment]
**Server Call Stack:**
```
python server.py
Generating x509 cert with message 'wait', data payload length 4

Enter a command type ('bash', 'exfil', 'kill'): bash
enter the bash command: ls
Generating x509 cert with message 'bash', data payload length 2
/root/Desktop/Research/exfil/secret_handshake/server.py:99: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  with ssl.wrap_socket(
Traceback (most recent call last):
  File "/root/Desktop/Research/exfil/secret_handshake/server.py", line 208, in <module>
    main()
  File "/root/Desktop/Research/exfil/secret_handshake/server.py", line 202, in main
    start_server(listen_addr, listen_port,
  File "/root/Desktop/Research/exfil/secret_handshake/server.py", line 146, in start_server
    client_msg, client_data = listen_for_client(listen_addr, listen_port, ca_cert_path, cmd_cert)
  File "/root/Desktop/Research/exfil/secret_handshake/server.py", line 99, in listen_for_client
    with ssl.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 1442, in wrap_socket
    return context.wrap_socket(
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
python client.py                                                                                                                                                                                           ─╯
Generating x509 cert with message 'request', data payload length 0
sleeping for 4 seconds
Server connection refused - trying again soon
sleeping for 5 seconds
Server connection refused - trying again soon
sleeping for 5 seconds
Server connection refused - trying again soon
sleeping for 3 seconds
Server connection refused - trying again soon
sleeping for 3 seconds
Server connection refused - trying again soon
sleeping for 4 seconds
Server connection refused - trying again soon
sleeping for 6 seconds
/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py:64: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
Traceback (most recent call last):
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 192, in <module>
    main()
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 176, in main
    start_client(
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 122, in start_client
    cert = call_server(host_addr, host_port, server_sni_hostname, ca_cert_path, next_msg_cert)
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 68, in call_server
    with context.wrap_socket(sock, server_side=False, server_hostname=server_sni_hostname) as secure_sock:
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:997)
```

**Call Stack for Client:**

```
python client.py                                                                                                                                                                                           ─╯
Generating x509 cert with message 'request', data payload length 0
sleeping for 4 seconds
Server connection refused - trying again soon
sleeping for 5 seconds
Server connection refused - trying again soon
sleeping for 5 seconds
Server connection refused - trying again soon
sleeping for 3 seconds
Server connection refused - trying again soon
sleeping for 3 seconds
Server connection refused - trying again soon
sleeping for 4 seconds
Server connection refused - trying again soon
sleeping for 6 seconds
/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py:64: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
Traceback (most recent call last):
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 192, in <module>
    main()
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 176, in main
    start_client(
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 122, in start_client
    cert = call_server(host_addr, host_port, server_sni_hostname, ca_cert_path, next_msg_cert)
  File "/home/kali/Desktop/Research/exfiltration/secret_handshake/client.py", line 68, in call_server
    with context.wrap_socket(sock, server_side=False, server_hostname=server_sni_hostname) as secure_sock:
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
**ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid** (_ssl.c:997)
```

**Comment by jconwell** [comment]
hmmm...I'm not getting that, but`cert_gen.gen_msg_cert` creates the message certs and has an optional argument `validity_end=1` that is used to set the `not_valid_after` date to `datetime.utcnow() + timedelta(days=validity_end)`. (cert_gen.py line 64-65). 

Try changing the `validity_end` argument to something like 7 (days) everywhere it's called in both client.py and server.py. Or just change the default value to 7.

Let me know if that fixes it and I'll change my repo. It should probably be something like 90 days anyway

**Comment by raghavmishra** [comment]
While debugging this issue I changed that to 365 in func argument in cert_gen.py but that didn't work though.

**Comment by jconwell** [comment]
I think what is happening is that `cert_gen.py line 64` sets the cert's `not_valid_before` date to `datetime.utcnow()`. But when the client validates the server's cert on `client.py line 68` the datetime written to the cert is before your's OS's current time somehow. That's why the error is `certificate is not yet valid`, which I thought was odd at first. 

You should be able to fix it by setting cert_gen.py line 64 to something like `.not_valid_before(datetime.utcnow())  - timedelta(days=10)`

If you could, I'd like you to test something. Could you run it again. Note when the datetime is of your OS when you run it, and then send me the generated server cert? I'd like to match the two datetimes and see what the difference is. I have no idea why it would do this though.

**Comment by raghavmishra** [comment]
This works. Since my server is in Cloud and geographically located somewhere in US so the time difference as you explained. Though, you need to replace this `.not_valid_before(datetime.utcnow())  - timedelta(days=10)` to `.not_valid_before(datetime.utcnow()  - timedelta(days=10))` otherwise you will get attribute error.

```
date && python server.py
Fri Jan 13 06:37:15 AM UTC 2023
Generating x509 cert with message 'wait', data payload length 4

Enter a command type ('bash', 'exfil', 'kill'): bash
enter the bash command: ls
Generating x509 cert with message 'bash', data payload length 2
/root/Desktop/Research/exfil/secret_handshake/server.py:99: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  with ssl.wrap_socket(
Parsed x509 cert with message 'request', data payload length 0
client requested command
Parsed x509 cert with message 'response', data payload length 161
client response:
	asn1_null_fields.py
	assets
	cert_gen.py
	certs
	client.py
	LICENSE
	Pipfile
	Pipfile.lock
	__pycache__
	README.md
	requirements.txt
	server.py
	super_valuable_files
	util.py
```

**Comment by jconwell** [comment]
oh good! glad that got you working. I'll make the change in my source for anyone else running a similar environment. Might add some randomness too. Thanks!
